### PR TITLE
Fix issue, option are not pass to the Detector

### PR DESCRIPTION
**Pull request by 5im0n**
Give to the Detector the correct option object

### CODE REVIEW

**Comment by Semigradsky** [comment]
Thanks! I see that the interface had changed. I will correct it and publish new version to npm soon.

**Comment by 5im0n** [comment]
Thank's Dmitry :thumbsup:

**Comment by Semigradsky** [comment]
New version here!
Hello semver :smile:

**Comment by 5im0n** [comment]
Greats,
:dog2: Buddy ready to find magic numbers

**Comment by callumacrae** [comment]
screen shot 2015-05-07 at 16 25 32

It was fixed before I even noticed it! :yum:

**Pull request merged**
